/**
 * US-5.2's cost-over-time series (S14 plan §4.1). Pure, `src/model/`: no i18n
 * import, no DOM, no clock. Zone and range are always parameters.
 *
 * `bucketRows` is the single bucketing rule `report.ts` also uses for
 * `byDay` / `byMonth` / `undated` (S14 plan §2 Q9) — one implementation two
 * consumers were previously duplicating.
 */
import { dayStringsOf, type DateRange } from "./date-range.js";
import type { SessionRow, TimeBucket, UndatedTotals } from "./report-types.js";
import { dayKey, monthKey, parseTimestamp, type ZoneOffsetResolver } from "./time-buckets.js";

export type Granularity = "day" | "month";

/** Max points a FILLED series may contain (Q5). ~3 years of days. */
export const MAX_TREND_POINTS = 1100;

export interface TrendPoint extends TimeBucket {
  /** True when this point was generated by gap-filling (no data at all). */
  readonly isZero: boolean;
  /**
   * (cost - prevCost) / prevCost against the PREVIOUS point in the ascending
   * array. null for the first point and whenever the previous cost is 0 —
   * never Infinity, never NaN (Q7).
   */
  readonly deltaRatio: number | null;
  /** cost / series costMicroUsd; 0 when the series total is 0. */
  readonly share: number;
}

export interface TrendSeries {
  readonly granularity: Granularity;
  /** Key ascending, ALWAYS — the UI reverses for display (Q6). Frozen. */
  readonly points: readonly TrendPoint[];
  /** Sum over points. NOT authoritative on its own — see `undated`. */
  readonly costMicroUsd: number;
  readonly requests: number;
  /** Scoped undated requests; they belong to no bucket (Q8). */
  readonly undated: UndatedTotals;
  /** False when the fill window would exceed MAX_TREND_POINTS (Q5). */
  readonly filled: boolean;
}

interface BucketAccumulator {
  costMicroUsd: number;
  requests: number;
  durationMs: number;
}

/**
 * Observed buckets only, key ascending. The single bucketing rule — also what
 * `buildReport` uses for `byDay` / `byMonth` / `undated` (Q9).
 */
export function bucketRows(
  rows: readonly SessionRow[],
  granularity: Granularity,
  zone: ZoneOffsetResolver,
): { readonly buckets: readonly TimeBucket[]; readonly undated: UndatedTotals } {
  const map = new Map<string, BucketAccumulator>();
  let undatedRequests = 0;
  let undatedCostMicroUsd = 0;

  for (const row of rows) {
    for (const request of row.requests) {
      const epochMs = parseTimestamp(request.timestamp);
      if (epochMs === null) {
        undatedRequests += 1;
        undatedCostMicroUsd += request.costMicroUsd;
        continue;
      }
      const key = granularity === "day" ? dayKey(epochMs, zone) : monthKey(epochMs, zone);
      let bucket = map.get(key);
      if (bucket === undefined) {
        bucket = { costMicroUsd: 0, requests: 0, durationMs: 0 };
        map.set(key, bucket);
      }
      bucket.costMicroUsd += request.costMicroUsd;
      bucket.requests += 1;
      bucket.durationMs += request.durationMs;
    }
  }

  const buckets = [...map.entries()]
    .sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))
    .map(([key, bucket]) => Object.freeze({ key, ...bucket }));

  return Object.freeze({
    buckets: Object.freeze(buckets),
    undated: Object.freeze({ requests: undatedRequests, costMicroUsd: undatedCostMicroUsd }),
  });
}

function pad(value: number, width: number): string {
  return String(Math.abs(value)).padStart(width, "0");
}

function splitDayKey(key: string): { y: number; m: number; d: number } {
  return { y: Number(key.slice(0, 4)), m: Number(key.slice(5, 7)), d: Number(key.slice(8, 10)) };
}

function formatDayKey(y: number, m: number, d: number): string {
  return `${pad(y, 4)}-${pad(m, 2)}-${pad(d, 2)}`;
}

function splitMonthKey(key: string): { y: number; m: number } {
  return { y: Number(key.slice(0, 4)), m: Number(key.slice(5, 7)) };
}

function formatMonthKey(y: number, m: number): string {
  return `${pad(y, 4)}-${pad(m, 2)}`;
}

/**
 * "2026-09-17" -> "2026-09-18"; "2026-12" -> "2027-01". Pure calendar
 * arithmetic. Day arithmetic goes through `Date.UTC` / `getUTC*` ONLY to let
 * it normalise a day one past the end of its month (implementation note 1) —
 * the key is already expressed in the resolved zone, so this never touches
 * `zone` again. Month arithmetic is deliberately `y * 12 + (m - 1)`
 * (implementation note 2): no `Date` involved, so no DST case and no
 * month-length case can exist in it.
 */
export function nextKey(key: string, granularity: Granularity): string {
  if (granularity === "day") {
    const { y, m, d } = splitDayKey(key);
    const next = new Date(Date.UTC(y, m - 1, d + 1));
    return formatDayKey(next.getUTCFullYear(), next.getUTCMonth() + 1, next.getUTCDate());
  }
  const { y, m } = splitMonthKey(key);
  const total = y * 12 + (m - 1) + 1;
  return formatMonthKey(Math.floor(total / 12), (total % 12) + 1);
}

/** Inclusive day count between two "YYYY-MM-DD" keys, fromKey <= toKey. */
function dayCount(fromKey: string, toKey: string): number {
  const f = splitDayKey(fromKey);
  const t = splitDayKey(toKey);
  const diffMs = Date.UTC(t.y, t.m - 1, t.d) - Date.UTC(f.y, f.m - 1, f.d);
  return Math.round(diffMs / 86_400_000) + 1;
}

/** Inclusive month count between two "YYYY-MM" keys, fromKey <= toKey. */
function monthCount(fromKey: string, toKey: string): number {
  const f = splitMonthKey(fromKey);
  const t = splitMonthKey(toKey);
  return t.y * 12 + t.m - (f.y * 12 + f.m) + 1;
}

/** The window boundary key on one side of the range, or null when unbounded. */
function boundaryKey(dayString: string | null, granularity: Granularity): string | null {
  if (dayString === null) {
    return null;
  }
  return granularity === "day" ? dayString : dayString.slice(0, 7);
}

function attachDerived(points: readonly Omit<TrendPoint, "deltaRatio" | "share">[]): {
  readonly points: readonly TrendPoint[];
  readonly costMicroUsd: number;
  readonly requests: number;
} {
  const totalCost = points.reduce((sum, p) => sum + p.costMicroUsd, 0);
  const totalRequests = points.reduce((sum, p) => sum + p.requests, 0);
  const withDerived = points.map((point, index) => {
    const prevCost = index > 0 ? points[index - 1]!.costMicroUsd : null;
    const deltaRatio =
      index === 0 || prevCost === null || prevCost === 0
        ? null
        : (point.costMicroUsd - prevCost) / prevCost;
    const share = totalCost === 0 ? 0 : point.costMicroUsd / totalCost;
    return Object.freeze({ ...point, deltaRatio, share });
  });
  return { points: Object.freeze(withDerived), costMicroUsd: totalCost, requests: totalRequests };
}

/**
 * The display series: buckets, zero-filled across the window, with `share` and
 * `deltaRatio`. `range` decides the window ends (Q4): a bounded side pins that
 * end, an unbounded side falls back to the first/last observed bucket. Returns
 * `filled: false` and the observed buckets unchanged when the window would
 * exceed MAX_TREND_POINTS.
 */
export function buildTrend(
  rows: readonly SessionRow[],
  granularity: Granularity,
  zone: ZoneOffsetResolver,
  range: DateRange,
): TrendSeries {
  const { buckets, undated } = bucketRows(rows, granularity, zone);
  const observedMap = new Map(buckets.map((bucket) => [bucket.key, bucket] as const));

  const firstObserved = buckets.length > 0 ? buckets[0]!.key : null;
  const lastObserved = buckets.length > 0 ? buckets[buckets.length - 1]!.key : null;

  const { from: boundFromDay, to: boundToDay } = dayStringsOf(range, zone);
  const startKey = boundaryKey(boundFromDay, granularity) ?? firstObserved;
  const endKey = boundaryKey(boundToDay, granularity) ?? lastObserved;

  if (startKey === null || endKey === null) {
    return Object.freeze({
      granularity,
      points: Object.freeze([]),
      costMicroUsd: 0,
      requests: 0,
      undated,
      filled: true,
    });
  }

  const count = granularity === "day" ? dayCount(startKey, endKey) : monthCount(startKey, endKey);

  if (count < 1) {
    // Defensive only (NFR-3): a real caller's window is never inverted, since
    // the rows a report hands buildTrend already lie inside `range`.
    return Object.freeze({
      granularity,
      points: Object.freeze([]),
      costMicroUsd: 0,
      requests: 0,
      undated,
      filled: true,
    });
  }

  if (count > MAX_TREND_POINTS) {
    const observedPoints = buckets.map((bucket) =>
      Object.freeze({ ...bucket, isZero: false, deltaRatio: null, share: 0 }),
    );
    const derived = attachDerived(observedPoints);
    return Object.freeze({
      granularity,
      points: derived.points,
      costMicroUsd: derived.costMicroUsd,
      requests: derived.requests,
      undated,
      filled: false,
    });
  }

  const rawPoints: Omit<TrendPoint, "deltaRatio" | "share">[] = [];
  let key = startKey;
  for (let i = 0; i < count; i += 1) {
    const observed = observedMap.get(key);
    rawPoints.push({
      key,
      costMicroUsd: observed?.costMicroUsd ?? 0,
      requests: observed?.requests ?? 0,
      durationMs: observed?.durationMs ?? 0,
      isZero: observed === undefined,
    });
    if (i < count - 1) {
      key = nextKey(key, granularity);
    }
  }

  const derived = attachDerived(rawPoints);
  return Object.freeze({
    granularity,
    points: derived.points,
    costMicroUsd: derived.costMicroUsd,
    requests: derived.requests,
    undated,
    filled: true,
  });
}
